import type { Metadata } from 'next';
import { Figtree } from 'next/font/google';
import './globals.css';
import localFont from 'next/font/local';
const figtree = Figtree({
    display: 'swap',
    subsets: ['latin'],
    weight: ['300', '400', '500', '600', '700', '800', '900'],
    variable: '--font-figtree',
});
const yekanbakh = localFont({
    src: [
        {
            path: '../../public/fonts/yekanBakh/YekanBakh-Thin.ttf',
            weight: '100',
            style: 'normal',
        },
        {
            path: '../../public/fonts/yekanBakh/YekanBakh-Light.ttf',
            weight: '300',
            style: 'normal',
        },
        {
            path: '../../public/fonts/yekanBakh/YekanBakh-Regular.ttf',
            weight: '400',
            style: 'normal',
        },
        {
            path: '../../public/fonts/yekanBakh/YekanBakh-SemiBold.ttf',
            weight: '600',
            style: 'normal',
        },
        {
            path: '../../public/fonts/yekanBakh/YekanBakh-Bold.ttf',
            weight: '700',
            style: 'normal',
        },
        {
            path: '../../public/fonts/yekanBakh/YekanBakh-Black.ttf',
            weight: '900',
            style: 'normal',
        },
    ],
    variable: '--font-yekanbakh',
});
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html>
            <body
                className={`${figtree.className} ${yekanbakh.className} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}

